name: Danner Lacrosse Uploader
on:
  workflow_dispatch:

jobs:
  run_dannerlac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DANNERLAC script
        env:
          D_USERNAME_SECRET: ${{ secrets.D_USERNAME_SECRET }}
          D_PASSWORD_SECRET: ${{ secrets.D_PASSWORD_SECRET }}
        run: python dannerlac.py

      - name: Commit and Push Downloaded File for DANNERLAC
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Downloads/
          git commit -m "Add downloaded file for DANNERLAC"
          git push https://${{ secrets.GH_PAT }}@github.com/Chrisodrogla/Scrape_Shopify-Product-Listing.git

  run_excel_to_csv:
    needs: run_dannerlac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies for EXCEL_TO_CSV
        run: pip install pandas openpyxl

      - name: Run data modification script for EXCEL_TO_CSV
        run: python dannerlac_data_editor.py

      - name: Commit and Push Modified File for EXCEL_TO_CSV
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Downloads/
          git commit -m "Add modified file for EXCEL_TO_CSV"
          git push https://${{ secrets.GH_PAT }}@github.com/Chrisodrogla/Scrape_Shopify-Product-Listing.git

  run_flx_upload:
    needs: run_excel_to_csv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies for FLX_Upload
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script for FLX_Upload
        env:
          FLX_USERNAME_SECRET: ${{ secrets.FLX_USERNAME_SECRET }}
          FLX_PASSWORD_SECRET: ${{ secrets.FLX_PASSWORD_SECRET }}
        run: python flxpoint.py

      - name: Commit and Push Archive File for FLX_Upload
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Archive/
          git commit -m "Add archive downloaded file for FLX_Upload"
          git push https://${{ secrets.GH_PAT }}@github.com/Chrisodrogla/Scrape_Shopify-Product-Listing.git

      - name: Commit and Push Downloaded File for FLX_Upload
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Downloads/
          git commit -m "Clear downloaded file for FLX_Upload"
          git push https://${{ secrets.GH_PAT }}@github.com/Chrisodrogla/Scrape_Shopify-Product-Listing.git
